# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Windows Master Build Validate

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 'latest'  # Use the latest version of Visual Studio

    - name: Build Solution
      # Build the solution using MSBuild
      run: msbuild DKEngine.sln /p:Configuration=Release
